[book]
authors = ["Steven Hé (Sīchàng)"]
language = "en"
multilingual = false
src = "src"
title = "mdbook-katex Static CSS Example"

[output.html]
# …
additional-css = ["katex.min.css"]

[output.katex]

[preprocessor.katex]
renderer = ["html"]
no-css = true
