name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure git
      run: |
        git config --global user.name "SichangHe"
        git config --global user.email "SichangHe@users.noreply.github.com"
    - name: Download and extract mdBook
      run: |
        tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
        url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        curl -o 'mdbook.tar.gz' -J -L $url
        tar -xzvf 'mdbook.tar.gz'
    - name: Download and extract mdBook-KaTeX
      run: |
        tag=$(curl 'https://api.github.com/repos/lzanini/mdbook-katex/releases/latest' | jq -r '.tag_name')
        url="https://github.com/lzanini/mdbook-katex/releases/download/${tag}/mdbook-katex-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        curl -o 'mdbook-katex.tar.gz' -J -L $url
        tar -xzvf 'mdbook-katex.tar.gz'
    - name: add bin to path
      run: echo "$(pwd)" >> $GITHUB_PATH
    - name: Download KaTeX CSS and fonts
      run: python3 download_static_css.py
    - name: Build
      run: mdbook build
    - name: push
      run: |
        git fetch
        git switch gh-pages
        rm -rf docs
        mv book docs
        git add docs
        git commit --allow-empty -m "Deploy $GITHUB_SHA to gh-pages"
        git push -f