name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure git
      run: |
        git config --global user.name "_"
        git config --global user.email "_@users.noreply.github.com"
    - name: Install mdBook 0.5.4
      run: |
        cargo install mdbook --version 0.5.4
    - name: Install mdBook-KaTeX
      run: cargo install --git https://github.com/SichangHe/mdbook-katex.git --rev f623f031d705ec96e5f747b8c3a910ef1a32734b --locked
    - name: add bin to path
      run: echo "$(pwd)" >> $GITHUB_PATH
    - name: Download KaTeX CSS and fonts
      run: python3 download_static_css.py
    - name: Build
      run: mdbook build
    - name: push
      if: github.event_name == 'push'
      run: |
        git fetch
        git switch gh-pages
        rm -rf docs
        mv book docs
        git add docs
        git commit --allow-empty -m "Deploy $GITHUB_SHA to gh-pages"
        git push -f
